(setq my-use-which-key t)
(setq my-use-orderless t)
(setq my-use-vertico t)
(setq my-use-consult t)
(setq my-use-projectile t)
(setq my-use-gfm-mode t)
(setq my-use-dired t)
(setq my-use-magit t)
(setq my-use-gtags-mode t)
(setq my-use-gxref t)
(setq my-use-lsp-mode t)
(setq my-use-lsp-ui t)
(setq my-use-lsp-ivy t)
(setq my-use-lsp-treemacs t)
g
